#+TITLE: First java program input/output debugging and datatypes

* structure of a java file

- Name: every file that ends with an extensions .java is a class itself; eg: main.java
  1. since it's name is main.java(or some name before ___.java) it should contain a class with that name (as in before the extension) in the file itself
  2. all the code that we'll be writing will be in this class main/name
- the Class in the name: remember if a variable name starts with a capital letter then it is a class name (by convention)
  1. If the class with the name of the file is in the file then that will be a class of the public type , in this case main is the public class type , public class means that this class will be accessible by all other files , classes, etc.
  2. Like cpp , java also has a main function (by convention) from where the program starts , whenever we run the program the compiler will look for main , if it is not present then the compiler will throw error.
  3. You can run with the java compiler "javac" _name_.java and then java _name_ (where name is the class as well as the file name) , also while running the executable(class file) with java you can use the class name only.

** explanation of the main.java file

#+begin_src java
public class main { // inside this block of {} is the int main of java as found in cpp
    public static void main(String[] args) {
        System.out.println("hello world!!");
    }
}
#+end_src
Here class is name group of properties and functions , in the above eg's class we have this function
*** /all about the function/
1. All the functions that are in the classes are knows as methods.
2. Also the function name has to be main only like here " public static void main(String[] args) " it is reserved to be here if it is not main it will not run since main function is the entry point of the function. c) Function is a block/collection of code which can be used again and again.
*** /then rest of the code explanation/
3. Here public means the same as in the class name part " public static void main(String[] args) " since main is necessary to run the program so it makes sense to make it available to be executed from anywhere i.e public class type , if we make it private then it will not be available like the public class and hence it will not be valid.
4. Here static means: this main function/method is a part of the _Main_ class also main is required to be run without creating an object of this Main class ,so we use the static type . Since nothing is running before the main() function then there is no use of making an object there.
5. Static variables and functions are the variables and functions that don't depend on the object.
6. void is the return type of the function, since we don't want any value here so we have used void(like in cpp).
*** /how to run/
7. (String[] args) are the arguments , collection of strings.
8. here args is the arguments given in the terminal with java command (like java Main 50 100 ...) after compiling with the javac(like javac Main(class/file name)) and the no inside the [] is the index of the array to which the values given with the java command will be printed , the values given with the java command is stored in the String[] array.
9. if you use javac -d _directory_ _name_: this -d flag is used to give a directory to store the .class file.
10. package is the folder where the java file will lie, eg package com.kunal , this com.kunal is a subfolder in the com folder (you can make more of those subfolders) , '.' period means subfolder.
11. then comes = System.out.println("hello world!!"); this line means (System.out) in the command line do a (.print(_string_)) this prints a string in the command line, if we use ctrl/cmd+click on this we get.
    #+begin_src java
/**
 ,* Prints a String and then terminate the line.  This method behaves as
 ,* though it invokes {@link #print(String)} and then
 ,* {@link #println()}.
 ,*
 ,* @param x  The {@code String} to be printed.
 ,*/
public void println(String x) {
    if (getClass() == PrintStream.class) {
        writeln(String.valueOf(x));
    } else {
        synchronized (this) {
            print(x);
            newLine();
        }
    }
}
    #+end_src

12. to print stuff we have the _System_ class , it is in file called System.java(since System starts with a capital letter hence we know it is a class) in the java.lang package. All the stuff available in the lang package can be accessed in the files created by the people who made java
13. _println_ in the above src says that you will give a string and it'll print that string
14. _out_ is a variable contained in the System class, it is basically a type of PrintStream(will be expained later), and PrintStream has something called println. out is like a reference variable for PrintStream and by default value of the standard output stream i.e the out is the commandline i.e laptop (idk what that means) or the place where the output will be shown, out's original value is null (like this here) = public static final PrintStream out = null; which means that the output will be in the commandline but if we declare out = _some file or anything_ then it will take the output of that println into that file or something
15. *##* so it means System has a variable called out which is of type PrintStream and this out has a method/function called println, since out is of type PrintStream so println is also in PrintStream : in the standard output stream print something

16. *NOTE* some of the reference  which can be added to the code itself instead of here are done in the file mentioned here

17. for _input_ in Main.java the code: ~ Scanner input = new Scanner(System.in); ~  _Scanner_ is a public class (it allows us to take input in simple sense) which is a simple text scanner which can parse primitive types and strings using regular expressions, then the _input_ is a normal declared variable and by using Scanner , this input will read everything we want ,then we add a new object i.e 'new' which is a keyword then Scanner(), in the brackets here we need to pass from where we will pass the input (can be a file or keyboard), we pass the System.in which is used to pass standard input or output (_.in_ part refers to the keyboard input) also the default value of System.in is null we can also define it to be something else . object is a type of scanner and it has a value of System.in whenever input asks for something you will take the value from the keyboard this is the meaning ; again scanner is basically a class that specifies an input stream and using the variable (object) of the class we can take input.
    /also look for the main documentation in the IntellijIdea by ctrl+click/

    - better explanation of the *System* class: The System class contains several useful class fields and methods. It cannot be instantiated. Among the facilities provided by the System class are standard input, standard output, and error output streams; access to externally defined properties and environment variables; a means of loading files and libraries; and a utility method for quickly copying a portion of an array.
    - and of the *.in* part: The "standard" input stream. This stream is already open and ready to supply input data. Typically this stream corresponds to keyboard input or another input source specified by the host environment or user. In case this stream is wrapped in a java.io.InputStreamReader, Console.charset() should be used for the charset, or consider using Console.reader().

18.  regarding the new keyword , it is used to

19. every class in java extends the object class , eg: Scanner ; important concept
20. about the different next( ,Int,ln) variants
        #+begin_src java
        System.out.println(input.nextInt()); // = nextInt prints the integer output
        System.out.println(input.next()); // = next prints the first string(/word) of a sentence of the input in the output
        System.out.println(input.nextln()); // = nextln prints the whole string of a sentence of the input in the output
        #+end_src

    /input is a variable pointing to the object of scannner class so it'll contain all the functions provided by the scanner class ; whatever input will be given it will be shown in output/

** All about the datatypes
1. Primitive data types are the ones which cannot be further broken into other datatypes . eg: "Kunal" this word can be further divided into individual letters i.e the string can be divided into char , but the char cannot be further divided into other data types, this last datatype which cannot be divided into further data type is known as primitive
2. *NOTE* To know why we are adding f to float and L to long at their respective end of the data type declaration value , we need to know the size of the bitwise operators ( also the range of them will be in the bitwise operators ),
   for now the size are : int and float has 4 bytes, double and long has 8 bytes
   a. All the decimal values are of the type _double_ by default so if there is a need to store them in float then we need to add an 'f' (remember lower case f only) after the end of the value
      /as to why use double instead of float: float gives floating point errors sometimes by rounding off numbers, so to get more accurate value we use double/
      also we can  store larger decimal values using the double type
   b. And the by default declaration type of integer values is _"int"_ so we use 'L' (remember upper case L only) at the end of the long type,
      /why use long instead of int: because it can store more/long integer values/
3. There contains a class for every data type known as wrapper classes for giving additional funtionality to the primitive datatypes, and they are written as
        #+begin_src java
        Integer rollno = 8;
        String name = "tera baap hu";
        #+end_src
   a. as you can see it contains the capital first letter which by convention means classes so all the other datatypes are written like the above example ( more on that later on OOPs )

   b. how to _comment_:  you can add single line comments using "/" and multi line comments using the following
        #+begin_src java
        /* this is a multi line
        comment
        ,*/
        #+end_src

** explanation for the inputs.java file (some are in the file itself)
1. you can use debugging to see how each line is executed one by one, also add breakpoints to make sure which lines you want to debug
2. about literals and identifiers:
        #+begin_src java
            int a = 10;
        #+end_src
   - here 10 is a _literal_, so in primitive datatypes literals are the syntactical representation of datatypes, i.e it can be used to represent specific values of a datatype and
   - and a, the _reference variable_ is known as the _identifier_, so it's basically the name of the identifier, variable, class, packages, or other stuff like interfaces in java, etc
3. int values can be given in a long form by adding some underscores (eg 100_100_09707) which gets ignored while running
4. nextFloat() takes float values, just like that you can end the after next___ underline part with the datatype which you want to get some input about, see completion for some help
5. + is used to join the sentences or strings together in "" as well as with the value of the variable ( as shown in the sum2nos.java file )

** explanation for the sum2nos.java file (some are in the file itself)
#+begin_src java
public static void main(String[] args){
    Scanner num = new Scanner(System.in);
    float input = num.nextFloat();
    System.out.println(input);
}
#+end_src
*** TypeCasting and TypeConversion
When we give int values in float datatype and after getting the output we see the result as 105.0 ( for c = 5).Because the int input is being converted to float, this is auto type conversion.
1. So when one type of data is assigned to another type of variable, then auto type conversion will take place if the following conditions are met
   a. the two types should be compatible, for ex = int and float, etc.
   b. the destination type should be greater than the source type be it in the declaration value or the input value, for ex = here int is smaller than float so float converts to int but vice versa is false. Asking for int but giving float won't work since int<float
   c. java does auto type conversion when it stores an integer constant into a variable of types like byte, short, long, and char sometimes , takes the ascii value of that
   d. *so how to convert int to float* - this is known as typecasting or casting in compatible types. It is used as the auto type conversion is helpful but it might not fulfill all the needs, for example - if you want to assign an integer variable to a byte variable or a float value to an integer variable(this will not happen auto, since they are greater than the other). This is sometimes called narrowing conversion since it tells the float value to narrow down the float value to integer
      - it is done as in the following block of code . It is compressing a bigger number into a smaller type explicitly, it says convert it into an integer hence the decimal part will get removed. The following is in the case of integers
        #+begin_src java
            int num = (int)(89.5f);
        #+end_src
      - also if a datatype can't handle the value as given to it, then it will print the modulo of the given value to the one that it can store. eg = for a given value 257 to byte , it will give 257 % 256 = _1_
   e. In the following code block, the byte format is converted to the int type first due to the following reasons
      #+begin_src java
            byte a = 40;
            byte b = 50;
            byte c = 100;
            int d = (a * b) / c;
      #+end_src
      In the code provided, the expressions a * b and (a * b) / c involve operands of type byte. However, the result of these expressions is automatically promoted to type int before being assigned to the variable d. This is because the Java language specifies that arithmetic operations involving byte, short, or char operands are performed using int arithmetic, and the result is automatically promoted to type int.

      So, in the line int d = (a * b) / c;, the expression (a * b) is evaluated first, and the result of this expression is an int value, since the operands a and b are promoted to type int before the multiplication is performed. The result of this multiplication, which is 2000, is then divided by the byte value 100, resulting in an int value of 20.

      The result of the expression (a * b) / c is an int value, and this value is assigned to the int variable d. The fact that d is declared as an int does not affect the promotion of the byte operands to int before the arithmetic operations are performed.

      So, the value of d is 20, which is an int value. The fact that a, b, and c are declared as byte variables does not affect the type of the result, which is automatically promoted to int.
   f. In the code ' int number = 'A', it converts the int type to the ascii value equivalent, so the this is also an example of the auto type conversion
   g. java following unicode principles, so any type of language/emoji/other unicode characters can be printed using java

**** Rules for the type conversion
1. all the byte, short and chararcter are promoted to integer types
2. if any one of the operands (i.e + / - / division/ x ) has the long type then the whole operation will be promoted to long, if it is float then the whole operation will be promoted to float, and if double then it will be promoted to double.
   eg : System.out.println(3 * 5.620389472987f); // prints output 16.861168 (since the f flag is added after the decimal number so it'll print float value so the value is rounded off, but if f flag is not given then the output will not be rounded off since it is double by default)

** explanation of the summary.java file ( summary of the whole video )
#+begin_src java
double result = (f * b) + (i / c) - (d - s); // two individual results of the operations
System.out.println((f * b) + " " + (i / c) + " " + (d - s));
System.out.println(result); // main output
#+end_src
here the float, byte, integer, char, double, short are declared and the result stores the value of the operation, first system.out prints the individual results of the operations separated by + and - and then the next system.out prints the total result of the whole
1. here in f * b prints the biggest of the two, so the float value is printed
2. here in i / c prints the biggest of the two, so the int value is printed
3. here in d - s prints the biggest of the two, so the double value is printed
4. *here* in short the if we have multiple types then all the others are converted to the biggest one
   in the main output , we got "float + int - double = double" we see that the result gets converted to double i.e the biggest one

** explanation of the Basics.java file ( summary of the whole video )
1. exp of if condition is in the file itself
2. exp of while condition is in the file itself
3. when you don't know how many times the loop is going to run use the while loop
4. when you know how many times the loop is going to run use the for loop
