install.packages("magick")
library(magick)
img <- image_read("/home/sunny/Pictures/nothing.png")
img_resized <- image_resize(img, "224x224")
img_gray <- image_convert(img_resized, colorspace = "gray")
img_normalized <- image_modulate(img_gray, brightness = 100, saturation = 100, hue =
100)
img_blurred <- image_blur(img_normalized, radius = 5)
img_equalized <- image_equalize(img_blurred)
img_flipped <- image_flip(img_equalized)
img_rotated <- image_rotate(img_flipped, 45)
img_cropped <- image_crop(img_rotated, "150x150+25+25")
img_padded <- image_border(img_cropped, "white", "10x10")
img_channel <- image_channel(img_padded, "red")
img_binary <- image_threshold(img_channel, threshold = "50%")
print(img_binary)
image_write(img_binary, "/home/sunny/Pictures/processed_image.jpg")
options(browser = "/usr/bin/brave")
browseURL("/home/sunny/Pictures/processed_image.jpg")
